### ISSUE TITLE
Drop in replacement?

### ISSUE THREAD

**Issue by wuast94** [pgautoupgrade/docker-pgautoupgrade#1]
Just for clarification, is this a "drop in" replacement for official postgress container? are variables paths etc the same? anything to look for?

**Comment by justinclift** [comment]
In theory (!) yes.

It's the official postgres `15.3-alpine3.18` Docker image + the older versions of PostgreSQL compiled into it and some `pg_upgrade` scripting added to the docker entrypoint script to run the upgrade.

If you're good with the `15.3-alpine3.18` build, then this should run fine.

That being said, this hasn't had wide use yet so it's probably best to make sure anything you're running with this has good backups happening on schedule.

I'm not *expecting* problems, more just in case... :smile:

**Comment by wuast94** [comment]
I will test this on a synapse and some bridge servers, have Backups and if something brakes no data is lost, let's say no data that Cares me much. Let's see what happens 🤪

**Comment by justinclift** [comment]
Awesome! :smile:

**Comment by justinclift** [comment]
Is the "some that was on Debian before complained a bit" stuff something that would be practical to detect and do something useful for?

**Comment by wuast94** [comment]
i see in my logs `database "postgres" has no actual collation version, but a version was recorded`

**Comment by justinclift** [comment]
Interesting, thanks.  I'll take a look later on today. :smile:

**Comment by justinclift** [comment]
Ok, it'll have to be this wkend when I look at this.  I have a reasonable idea of what the message is about, and it shouldn't be too hard to fix.  In theory.

**Comment by wuast94** [comment]
There seems to be a collation mismatch, my db uses C and C dont have a version if i understand it right

![grafik](https://github.com/justinclift/docker-pgautoupgrade/assets/16965460/8dd9c45e-82af-4704-b179-29bb5ad6a9da)

**Comment by justinclift** [comment]
Yeah, that's pretty my thinking of the cause as well.

The solutions is *probably* going to be some changes to this line where it does the initdb:

https://github.com/justinclift/docker-pgautoupgrade/blob/93629ba0fcf59a9bbc05265838345f58cc1a0da9/docker-entrypoint.sh#L368

So, instead of doing it blindly like that, we'll need to first determine the collation for the existing database (may need to temporarily start the old version?), then we can run `initdb` and pass it the same collation info so things match up.

From the `initdb` --help output:

```
      --no-locale           equivalent to --locale=C
      --icu-locale=LOCALE   set ICU locale ID for new databases
      --locale=LOCALE       set default locale for new databases
      --lc-collate=, --lc-ctype=, --lc-messages=LOCALE
      --lc-monetary=, --lc-numeric=, --lc-time=LOCALE
                            set default locale in the respective category for
                            new databases (default taken from environment)
```

So for the `C` locale it'd just be the first one `--no-locale`.

This is all just theory though.  It *probably* will work like this, but until we've tried it and confirmed it works... :smile:

**Comment by wuast94** [comment]
if i can help you testing this say what i have to do 😊 but sounds like it could work

**Comment by justinclift** [comment]
Thanks.  I won't have time to try implementing it for several hours, and it might be a tomorrow thing instead though.  Just so you know. :smile:

**Comment by justinclift** [comment]
Taking an initial look at this, so dumping some rough notes and thoughts here for now.

---

There seem to be several different ways of getting the collation info for a given database out of PostgreSQL.

For example:

```
$ psql database_name
# SELECT * FROM pg_database;

 oid |  datname  | datdba | encoding | datlocprovider | datistemplate | datallowconn | datconnlimit | datfrozenxid | datminmxid | dattablespace | datcollate |  datctype  | daticulocale | datcollversion |               datacl                
-----+-----------+--------+----------+----------------+---------------+--------------+--------------+--------------+------------+---------------+------------+------------+--------------+----------------+-------------------------------------
   5 | postgres  |     10 |        6 | c              | f             | t            |           -1 |          717 |          1 |          1663 | en_US.utf8 | en_US.utf8 |              |                | 
   1 | template1 |     10 |        6 | c              | t             | t            |           -1 |          717 |          1 |          1663 | en_US.utf8 | en_US.utf8 |              |                | {=c/postgres,postgres=CTc/postgres}
   4 | template0 |     10 |        6 | c              | t             | f            |           -1 |          717 |          1 |          1663 | en_US.utf8 | en_US.utf8 |              |                | {=c/postgres,postgres=CTc/postgres}
```

From that, the `datcollate`, `datctype`, `daticulocale`, and `datcollversion` columns seem relevant.

The problem there is it doesn't seem to really tell us what the default locale and collation pieces are for the database cluster.

What *seems* to work for doing that, are the `SHOW LC_COLLATE` and `SHOW LC_CTYPE` commands:

```
# SHOW LC_COLLATE;
 lc_collate 
------------
 en_US.utf8
(1 row)

# SHOW LC_CTYPE;
  lc_ctype  
------------
 en_US.utf8
(1 row)
```

They can also be run with PostgreSQL in single user mode.  Example from a PG 9.5 database using the `C` collation:

```
$ /usr/local-pg9.5/bin/postgres --single -D /var/lib/postgresql/data/ninefive

PostgreSQL stand-alone backend 9.5.25
backend> SHOW LC_COLLATE;
         1: lc_collate  (typeid = 25, len = -1, typmod = -1, byval = f)
        ----
         1: lc_collate = "C"    (typeid = 25, len = -1, typmod = -1, byval = f)
        ----
backend> SHOW LC_CTYPE;
         1: lc_ctype    (typeid = 25, len = -1, typmod = -1, byval = f)
        ----
         1: lc_ctype = "C"      (typeid = 25, len = -1, typmod = -1, byval = f)
        ----
```

So, with some shell pipelining we can work things out:

```
$ echo 'SHOW LC_COLLATE' | /usr/local-pg9.5/bin/postgres --single -D /var/lib/postgresql/data/ninefive | grep 'lc_collate = "' | cut -d '"' -f 2
C
$ echo 'SHOW LC_CTYPE' | /usr/local-pg9.5/bin/postgres --single -D /var/lib/postgresql/data/ninefive | grep 'lc_ctype = "' | cut -d '"' -f 2
C
```

Trying that again, with a PG 9.5 data directory initialised with `en_US.UTF-8` works as well:

```
$ echo 'SHOW LC_COLLATE' | /usr/local-pg9.5/bin/postgres --single -D /var/lib/postgresql/data/ninefive | grep 'lc_collate = "' | cut -d '"' -f 2
en_US.UTF-8
05c67bf06846:~$ echo 'SHOW LC_CTYPE' | /usr/local-pg9.5/bin/postgres --single -D /var/lib/postgresql/data/ninefive | grep 'lc_ctype = "' | cut -d '"' -f 2
en_US.UTF-8
```

This seems like a workable way forward.

**Comment by wuast94** [comment]
I think the main problem is to change the collation not to get the info what the actual used and initialized is. 

I'm on the road ATM so will have a deeper look later. 

And now worries, it's not a time critical thing, so take your time, you doing this in your free time, so no pressure ☺️

**Comment by justinclift** [comment]
> I think the main problem is to change the collation not to get the info what the actual used and initialized is.

Nah.  The default collation is set when the `initdb` is run, so we might as well just get the details for the old one and copy use that.  That's my thinking (so far) anyway. :smile:

**Comment by justinclift** [comment]
Actually, thinking about it more the `initdb` style change is probably only going to be good for databases that haven't been auto-upgraded yet.

So, for those that have and had their locale changed (this the version mismatch message)... yeah, that's going to need something different done.

**Comment by justinclift** [comment]
> if i understand it right, the only thing i can do is dumb the db, recreate a fresh db and import the db back. but will wait what u say

That's probably going to be the most straight forward approach.  You'd likely need to look at the starting section of the `pg_dump` output (before importing) to potentially manually remove any collation setting statements.

**Comment by kenaniah** [comment]
I believe you should be able to use `pg_controldata` to determine the locale of a cluster without having to run the server.

**Comment by justinclift** [comment]
Thanks heaps @kenaniah, I'll try that out locally then update the script accordingly. :smile:

**Comment by justinclift** [comment]
@kenaniah Trying that just now, it does show a lot of information, but collation related info doesn't seem to be part of it:

```
$ which pg_controldata
/usr/local/bin/pg_controldata
$ pg_controldata -V
pg_controldata (PostgreSQL) 15.3
$ pg_controldata -D /var/lib/postgresql/data/old
WARNING: Calculated CRC checksum does not match value stored in file.
Either the file is corrupt, or it has a different layout than this program
is expecting.  The results below are untrustworthy.

pg_control version number:            942
Catalog version number:               201510051
Database system identifier:           7256631598560251934
Database cluster state:               shut down
pg_control last modified:             Mon Jul 17 03:56:50 2023
Latest checkpoint location:           0/1703AC0
Latest checkpoint's REDO location:    0/1703A50
Latest checkpoint's REDO WAL file:    01703AC00000000000000001
Latest checkpoint's TimeLineID:       24132288
Latest checkpoint's PrevTimeLineID:   0
Latest checkpoint's full_page_writes: on
Latest checkpoint's NextXID:          0:1
Latest checkpoint's NextOID:          620
Latest checkpoint's NextMultiXactId:  12377
Latest checkpoint's NextMultiOffset:  1
Latest checkpoint's oldestXID:        0
Latest checkpoint's oldestXID's DB:   612
Latest checkpoint's oldestActiveXID:  0
Latest checkpoint's oldestMultiXid:   1
Latest checkpoint's oldestMulti's DB: 1
Latest checkpoint's oldestCommitTsXid:0
Latest checkpoint's newestCommitTsXid:0
Time of latest checkpoint:            Mon Jul 17 03:56:50 2023
Fake LSN counter for unlogged rels:   0/1
Minimum recovery ending location:     0/0
Min recovery ending loc's timeline:   0
Backup start location:                0/0
Backup end location:                  0/0
End-of-backup record required:        no
wal_level setting:                    minimal
wal_log_hints setting:                off
max_connections setting:              100
max_worker_processes setting:         8
max_wal_senders setting:              0
max_prepared_xacts setting:           64
max_locks_per_xact setting:           0
track_commit_timestamp setting:       on
Maximum data alignment:               0
Database block size:                  8192
Blocks per segment of large relation: 131072
WAL block size:                       8192
Bytes per WAL segment:                16777216
Maximum length of identifiers:        64
Maximum columns in an index:          32
Maximum size of a TOAST chunk:        1996
Size of a large-object chunk:         2048
Date/time type storage:               64-bit integers
Float8 argument passing:              by value
Data page checksum version:           0
Mock authentication nonce:            6e7cd4bc00000000000000000000000000000000000000000000000000000000
```

**Comment by fOmey** [comment]
[justinclift](https://github.com/justinclift)

I'm a PG newbie and I've stumbled across the collation error.

Are there steps to manually resolve this until a fix is implemented? All the fix search results don't seem to be working.

**Comment by justinclift** [comment]
@fOmey What was the (exact) PostgreSQL image you were previously using?

I still need to look into this issue in detail, so I don't have any immediate suggestion right away.  But knowing the exact PG image you were previously using might lead to some useful suggestions. :smile:

**Comment by fOmey** [comment]
> @fOmey What was the (exact) PostgreSQL image you were previously using?
> 
> I still need to look into this issue in detail, so I don't have any immediate suggestion right away. But knowing the exact PG image you were previously using might lead to some useful suggestions. 😄

I would have been using the version before the latest.

**Comment by justinclift** [comment]
> I would have been using the version before the latest.

Sorry, that's a bit unclear.  Might have been my fault. :smile:

What version of PostgreSQL were you using before trying pgautoupgrade on your PostgreSQL data directory, and (it's important) where did you get that version of PostgreSQL from?

For example, there are several different Docker Hub repositories that can provide PostgreSQL, and there are non-Docker-Hub providers of PostgreSQL too. :smile:

**Comment by fOmey** [comment]
> > I would have been using the version before the latest.
> 
> Sorry, that's a bit unclear. Might have been my fault. 😄
> 
> What version of PostgreSQL were you using before trying pgautoupgrade on your PostgreSQL data directory, and (it's important) where did you get that version of PostgreSQL from?
> 
> For example, there are several different Docker Hub repositories that can provide PostgreSQL, and there are non-Docker-Hub providers of PostgreSQL too. 😄

All good, my mistake I should have been more clear.

I was using the official postgres image on dockerhub, latest tag: https://hub.docker.com/_/postgres/

I switched over to pgautoupgrade last month (Sep 17).

**Comment by justinclift** [comment]
Thanks, yeah that closer to the info I'm asking about. :smile:

In that repository, they have both Alpine Linux based images (eg `16-alpine`), and non alpine based ones.

Do you remember (exactly) what tag/image you were previously using?

I'm *guessing* it wasn't an Alpine based image, and the switch to an Alpine based one (aka pgautoupgrade) is a contributing factor.  But if you were actually using one of their Alpine based images, that'll mean a different thing is probably coming into play.

**Comment by justinclift** [comment]
> latest tag

Heh.  Just now that sank in. :smile:

So, looking at their list of tags is seems like `latest` is the equivalent to `bookworm`, which is a non-Alpine based image.

That'll mean the collation error is probably being caused (somehow) by the switch from glibc to musl as the base backend c library.  I haven't yet investigated how to fix that though, so I'm not really sure what you can try. :frowning:

**Comment by justinclift** [comment]
The info here is likely to be of use though:

https://wiki.postgresql.org/wiki/Locale_data_changes

At least, that's on my todo list for reading ~first when I next look into solving this.

**Comment by justinclift** [comment]
@wuast94 @kenaniah @fOmey If anyone's up for testing a new Debian based pgautoupgrade image, then @andyundso has officially added ones for PostgreSQL 15 and 16:

* `15-bookworm`
* `16-bookworm`

Anyone up for giving it a go then reporting back whether the collation weirdness is all fixed? :smile:

**Comment by wuast94** [comment]
From my side we can close this issue.
Its an Drop in replacement on the same arch. Switching from Debian to Alpine or vise versa you should always pay attention.
And as always, make backups and test afterwards. Feel free to open a specific issue when something dont work 😊

**Comment by justinclift** [comment]
Awesome.  Thanks heaps for testing @wuast94. :smile:
