### ISSUE TITLE
Postgres 16

### ISSUE THREAD

**Issue by dtcooper** [pgautoupgrade/docker-pgautoupgrade#14]
PostgreSQL 16 was just released! [See following](https://www.postgresql.org/about/news/postgresql-16-released-2715/). Would it be possible to upgrade this container?

Cheers!

**Comment by justinclift** [comment]
Yep, am planning on it in the next few days. :smile:

**Comment by justinclift** [comment]
@dtcooper @jd1 PostgreSQL 16 support has just been added.  It's passing the local test suite fine, and seems like it'll be good.

An initial Docker build with is on Docker Hub, using the `16-dev` tag.  Would either of you be up for trying it out with your stuff (on non-production data!), to verify it from your point of view?

Full tag name to use: `pgautoupgrade/pgautoupgrade:16-dev`

**Comment by justinclift** [comment]
That `16-dev` image is an x86_64 specific build, rather than built for all architectures.

I've just pushed an `arm64` specific build to this tag in case it's useful: `pgautoupgrade/pgautoupgrade:16-dev-arm64`

That one was built on an M1 Mac Mini running macOS.  So, should work on (at least) Apple Silicon based computers.

At some point I need to read the docker docs for creating multi-architecture images.  It's on my To do list, but probably won't happen this week.

**Comment by dtcooper** [comment]
You might consider using GitHub actions to build the containers automatically. I do that for several of my projects, and it supports multi-arch containers out-of-the-box.

If I have time I'll draw up a PR showing you how you might achieve it.

Cheers!

**Comment by justinclift** [comment]
Thanks, didn't know they do multi-arch stuff too.  That's good info. :smile:

I've just sent you a team invite, so you can try it out pretty directly if you want. :grin:

**Comment by schonert** [comment]
Anything we can do to push this forward? 🤓

**Comment by justinclift** [comment]
Oops, I forgot to mention it here when the `latest` tag was updated with PostgreSQL 16 a while back.

If you pull the `latest` build (or even a few weeks ago), it uses PG 16.

**Comment by schonert** [comment]
@justinclift great - thanks!

**Comment by justinclift** [comment]
As a data point, the pgautoupgrade images were updated to PostgreSQL 16.2 (and the latest revision of older releases) yesterday.

I'll close this issue as the main topic of it is done.  The concept of "lets get GitHub to automatically build the images" is already on the ToDo list.  Especially as we can (hopefully) get multi-architecture images happening on the way through. :smile:
