### ISSUE TITLE
can this be assembled using the images instead of building from source?

### ISSUE THREAD

**Issue by jjb** [pgautoupgrade/docker-pgautoupgrade#24]
thanks for a great project!

is something like this possible, so don't need to download and build source?

I'm sure you've thought of this already...

```dockerfile
FROM postgres:14-alpine3.19 as pg14

COPY --from=pg14 /usr/local-pg14 /usr/local-pg14 # or whatever
```

**Comment by justinclift** [comment]
Yeah, I'm pretty sure (hmmm, about 85% sure) that's one of the first things that I tried when putting together this docker image initially.

From rough memory, the reason it didn't work out that way was um... umm... uuuuummmm.... I *think* it was something like the binaries for the older versions (eg PG 9.x) didn't play well when added to the same system as the new ones.

That being said, it's entirely possible it was just something easily fixable and taking another look at it might work out. :smile:
