### ISSUE TITLE
image pgautoupgrade/pgautoupgrade:15-alpine upgrades database to postgres 16

### ISSUE THREAD

**Issue by mx-bernhard** [pgautoupgrade/docker-pgautoupgrade#28]
I thought that `pgautoupgrade/pgautoupgrade:15-alpine` was just ensuring that after the upgrade the database version was 15 and not 16 and `pgautoupgrade/pgautoupgrade:16-alpine` was doing the same but with database version 16 as a target. If I change `PGTARGET` environment variable to 15 before starting the container with image `pgautoupgrade/pgautoupgrade:15-alpine`, no upgrade is started. This is either a bug or a missing in the documentation (to me, it looks like the former). Starting `pgautoupgrade/pgautoupgrade:15-alpine` like this yields 16 and not 15:

```sh
docker run -it --rm pgautoupgrade/pgautoupgrade:15-alpine /bin/bash                                                                                 127 ↵  ⚡  10313  11:32:04
************************************
PostgreSQL data directory: /var/lib/postgresql/data
************************************
7814a82c00a5:/var/lib/postgresql# echo $PGTARGET
16
7814a82c00a5:/var/lib/postgresql#
```

**Comment by justinclift** [comment]
Oh crap.  Yeah, 15-alpine is supposed to upgrade stuff to *15*.

Definitely a bug.  We greatly changed the build process for images over the last 2 days in order to enable ARM64.  Looks like it's not quite right. :frowning_face:

@andyundso Are you ok to look into this?

**Comment by andyundso** [comment]
very sorry about that, was a mistake by me in the pipeline configuration. fixed with #29.

**Comment by justinclift** [comment]
Thanks @andyundso. :smile:

Super sorry about that @mx-bernhard. :frowning:

**Comment by andyundso** [comment]
fixed images are now available on Docker Hub.

```
$ docker pull pgautoupgrade/pgautoupgrade:15-alpine
$ docker run -d -it -e POSTGRES_PASSWORD=password --rm pgautoupgrade/pgautoupgrade:15-alpine
$ docker exec -it jovial_hoover psql -U postgres
psql (15.6)
Type "help" for help.

postgres=# exit
```

Really sorry about this mistake, I should have checked the Docker layers on Docker Hub and I would have seen the issue beforehand.

**Comment by mx-bernhard** [comment]
Nothing bad happened for me, I have backups, as one should. Also, I had time to investigate today. 👍 for fixing so fast.
