### ISSUE TITLE
New PG point release 16.4 (etc)

### ISSUE THREAD

**Issue by justinclift** [pgautoupgrade/docker-pgautoupgrade#38]
New PostgreSQL point release announced today: https://www.postgresql.org/docs/release/16.4/

I'll update the Dockerfile this weekend if no-one else gets to it first.

And we'll probably need to look into the disk space issue with the docker image building about then too. :smile:

**Comment by justinclift** [comment]
PostgreSQL version update committed in https://github.com/pgautoupgrade/docker-pgautoupgrade/pull/39

I'll close this issue now.  Not real sure how we're going to fix the image building disk space issue though.

**Comment by justinclift** [comment]
@andyundso As a general thought, do you reckon the disk space problem could be solved by us having the build script run some kind of `docker image prune -f`?  And maybe similar `volume`, and perhaps even `docker system prune -f` too?

**Comment by andyundso** [comment]
I need to see what takes up the disk space. I should be able to simulate this either with [act](https://github.com/nektos/act) or just run the commands manually inside a Docker container. will get back to you soon.

**Comment by justinclift** [comment]
Closing this now that @andyundso has fixed the disk space problem. :smile:
