### ISSUE TITLE
Error when updating a database that has a different Postgres user

### ISSUE THREAD

**Issue by Randy-Blancett** [pgautoupgrade/docker-pgautoupgrade#55]
I recently tried to use the Debian based version of your code to update a database that was created by the official Postgres Docker image.

That image used POSTGRES_USER to create a database owned by a different user. The Upgrade proceded with out issue until it hit the pgautoupgrade-postupgrade.sh script. Here it complained because the database was not owned by postgres. I manually updated the script to add the -U ${POSTGRES_USER} to the commands and it worked. 

I wanted to see if I am missing something or if this could be included in the script.

Additionally Every thing worked fine after that except when it tried to shutdown the DB it tried to run `pg_ctl stop` which is not a valid command on the Debian version of postgres Is this a known issue or am i doing something wrong?

Also wanted to say that this container is great It will be awesome to "automate" the postgres upgrade process.

**Comment by justinclift** [comment]
> I manually updated the script to add the -U ${POSTGRES_USER} to the commands and it worked.

Uh oh.  Sounds like we need to update the post-upgrade script.  And also update the automatic tests to include a database owned by a different user to catch script problems like that in future.

Thanks for pointing this out.

> it tried to run pg_ctl stop which is not a valid command on the Debian version of postgres

Uh oh, I'll need to investigate.  `pg_ctl` not being in the Debian version of the container sounds weird to me.

**Comment by justinclift** [comment]
`pg_ctl` is definitely present in the Debian version of the image.

Pulling down the `pgautoupgrade/pgautoupgrade:17-bookworm` image just now and looking in that:

```
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

`pg_ctl` is present:

```
# which pg_ctl
/usr/lib/postgresql/17/bin/pg_ctl
```

I'm putting together a quick fix for the username issue, though properly updating the CI tests to catch this problem in future is going to take more extensive effort as we'll need to change the test data source to something different.

**Comment by justinclift** [comment]
@Randy-Blancett I've just updated the post upgrade script to use the `POSTGRES_USER` environment variable, so _in theory_ this should now work for you.

Do you have time to try it out and report success/failure/etc? :smile:

**Comment by Randy-Blancett** [comment]
Yes, I will try it tonight. Thank you for the quick turnaround.
Randy Blancett

**Comment by justinclift** [comment]
Fantastic.  Thanks heaps for both reporting the problem, and verifying the fix works too @Randy-Blancett. :grin:
