### ISSUE TITLE
REINDEX fails

### ISSUE THREAD

**Issue by csrl** [pgautoupgrade/docker-pgautoupgrade#67]
```
------------------------
Reindexing the databases
------------------------
-------------------------------
Starting reindex of user
-------------------------------
2024-11-15 22:10:20.467 UTC [414] ERROR:  syntax error at end of input at character 30
2024-11-15 22:10:20.467 UTC [414] STATEMENT:  REINDEX DATABASE CONCURRENTLY
ERROR:  syntax error at end of input
LINE 1: REINDEX DATABASE CONCURRENTLY
```

The above error is repeated for every database.  It appears the database name is missing from the query.

The docker volume being updated was from a postgres:10.21 container.

Upgraded to 13 with:
```
sudo docker run --rm --name pgauto -it --mount type=bind,source=/var/lib/docker/volumes/<volume_id>/_data,target=/var/lib/postgresql/data -e POSTGRES_PASSWORD=postgres -e PGAUTO_ONESHOT=yes pgautoupgrade/pgautoupgrade:13-bookworm
```

At the end of it, the data exists and my new postgres:13 container can access the volume and data "fine" after I manually reindexed all the databases.  No obvious issues yet.  Also when manually reindexing, it wasn't possible to use the CONCURRENTLY statement. `REINDEX DATABASE user;` worked.

I don't find another issue in the tracker related to this.  But not sure why it would be unique to my case.

**Comment by justinclift** [comment]
Oh, I wonder if there's was a syntax difference with PG 13 reindexing compared to the more modern releases that we're weren't aware of.

If that's the case, it should be a fairly easy fix.  We'll take a look in the next few days, and your existing PG database should be functional anyway.

You can manually run a `REINDEX DATABASE` on each database in your setup to achieve the same thing.  That'll do some table locking while it runs, though if the database is fairly small and on SSDs then it won't take long to finish anyway.

Thanks for letting us know @csrl, that definitely helps. :smile:
