### ISSUE TITLE
any consideration  for a mod (or pull requests) for specific postgresql upgrade version targets?

### ISSUE THREAD

**Issue by jacquelynch** [pgautoupgrade/docker-pgautoupgrade#8]
Am considering not upgrading directly to 15 but to 14 or so.   This capability doesn't look to be present in latest tag at the moment so am seeing if it can be resolved with a local checkout unless there's a good  reason not to attempt  it?

**Comment by justinclift** [comment]
Hmmm, we could add a PG 14 docker image fairly simply.  It'll probably take a day or so for me to get to it though, if that's workable?

**Comment by justinclift** [comment]
No worries, it shouldn't be hard to do.

The PG 15 image uses this build process:

### 1. Start from the generic alpine 3.18 image as a base:

https://github.com/pgautoupgrade/docker-pgautoupgrade/blob/585a87d03365fa238915a933c24d1bf68c9af3f6/Dockerfile#L4

### 2. Compile "the other" versions of PG

https://github.com/pgautoupgrade/docker-pgautoupgrade/blob/585a87d03365fa238915a933c24d1bf68c9af3f6/Dockerfile#L12-L76

### 3. Copy the compiled PG pieces onto the desired official PG image

https://github.com/pgautoupgrade/docker-pgautoupgrade/blob/585a87d03365fa238915a933c24d1bf68c9af3f6/Dockerfile#L78-L88

So, as long as there's nothing weird going on, then doing the same for PG 13, 14, (etc) is likely to be the same process.  You could quite literally cut-n-paste the above Dockerfile, replace a few version numbers, and comment out the later PG version pieces.

The docker "entry point" script that does the version detection and upgrade piece is also a  fairly simple modification of the "official" Docker PG (alpine) one:

https://github.com/pgautoupgrade/docker-pgautoupgrade/blob/585a87d03365fa238915a933c24d1bf68c9af3f6/docker-entrypoint.sh#L352-L476

Again, just changing the version number and commenting out the stuff for newer PG versions is likely to be all it needs.

That's all "in theory" of course, but I kind of expect that should work out ok for this scenario. :smile:

**Comment by jacquelynch** [comment]
That's working nicely with your highlighted mods.  Thanks.  I'd note to anyone to be mindful of any docker override file you might have around and don't pay much attention to.   It could play a factor if it overwrites something your looking at closely.

**Comment by justinclift** [comment]
@jacquelynch Cool.  I've been putting a bit of time into this today as well:

https://github.com/pgautoupgrade/docker-pgautoupgrade/pull/9

It's still early stage "work in progress", but I'm hoping to have it finished up a few hours from now.  Would you be up for doing some testing of the resulting images (PG 13 & 14) in the next few days?

**Comment by justinclift** [comment]
There are now `13-dev` and `14-dev` tags on Docker Hub, with pgautoupgrade images for those two specific versions.

They both pass the initial automatic testing here (it's very simple though!).

If you have time to try them out and report back success/failure, that would be very welcome. :smile:
